apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt-go-grafana-app
  labels:
    app: app
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: tilt-go-grafana
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/part-of: tilt-go-grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        app.kubernetes.io/part-of: tilt-go-grafana
    spec:
      containers:
      - name: tilt-go-grafana
        image: tilt-go-grafana-image
        ports:
          - name: http
            containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: tilt-go-grafana
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: tilt-go-grafana
spec:
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: tilt-go-grafana
  ports:
    - name: http
      port: 8080