apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/part-of: tilt-go-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
      app.kubernetes.io/part-of: tilt-go-grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/part-of: tilt-go-grafana
    spec:                   
      containers:
        - name: promtail
          image: grafana/promtail:latest