apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: tilt-go-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/part-of: tilt-go-grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/part-of: tilt-go-grafana
    spec:                   
      containers:
        - name: loki
          image: grafana/loki:latest
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: tilt-go-grafana
spec:
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: tilt-go-grafana
  ports:
    - name: loki
      port: 3100