apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt-go-grafana-server
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: tilt-go-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: tilt-go-grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: tilt-go-grafana
    spec:      
      volumes:
        - name: ini-vol
          configMap:
            name: tilt-grafana-config
            items:
            - key: grafana.ini
              path: grafana.ini
        - name: provision-datasources-vol
          configMap:
            name: tilt-grafana-config
            items:
            - key: datasource-prometheus.yaml
              path: datasource-prometheus.yaml              
      containers:
        - name: grafana
          image: grafana/grafana:8.0.3
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: ini-vol
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: provision-datasources-vol
              mountPath: /etc/grafana/provisioning/datasources/datasource-prometheus.yaml
              subPath: datasource-prometheus.yaml
          readinessProbe:
            httpGet:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10